name: CI

on:
  schedule:
    - cron: '*/15 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Create and commit report
        env:
          CURRENT_HOUR: date +"$H"
          RANDOM_HOUR: $((( RANDOM % 24 )))
        if: $CURRENT_HOUR != $RANDOM_HOUR
        run: |
          echo 'Current Hour: $CURRENT_HOUR'
          echo 'Random Hour: $RANDOM_HOUR'
          date +%s > report.txt
          git config user.name 'stevewithington'
          git config user.email 'steve@digitalmine.com'
          git add .
          git commit -am 'Keeping my contibutions green!'
          git push
