name: CI

on:
  schedule:
    - cron: '*/30 * * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Create and commit report
        run: |
          current_hour=$(date +"%H")
          random_hour=$((( RANDOM % 24 )))

          if [[ "$current_hour" != "$random_hour" ]]; then
            echo 'Current Hour (' $current_hour ') does NOT match Random Hour (' $random_hour '), continuing commit ...'
            date +%s > report.txt
            git config user.name 'stevewithington'
            git config user.email 'steve@digitalmine.com'
            git add .
            git commit -am 'Keeping my contibutions green!'
            git push
          else
            echo 'Current Hour (' $current_hour ') MATCHES Random Hour (' $random_hour '), skipping commit!'
          fi
