name: CI

on:
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo " " >> README.md
          git config user.name {{USERNAME}}
          git config user.email {{EMAIL}}
          git add .
          git commit -m "Keeping my contributions green!"
          git push
          """
