name: CI

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Create report
        run: date +%s > report.txt

      - name: Commit report
        run: |
          git config user.name 'stevewithington'
          git config user.email 'steve@digitalmine.com'
          git add .
          git commit -am 'Keeping my contibutions green!'
          git push
